#include <emscripten/bind.h>
#include "Engine.h"

EMSCRIPTEN_BINDINGS(simulation)
{
    emscripten::value_object<Statistics>("Statistics")
        .field("totalDeersSlain", &Statistics::totalDeersSlain)
        .field("totalMealsCooked", &Statistics::totalMealsCooked)
        .field("totalMealsEaten", &Statistics::totalMealsEaten)
        .field("totalTreesChopped", &Statistics::totalTreesChopped);

    emscripten::class_<Engine>("Engine")
        .constructor<uint32_t, int, int, int>()
        .function("simulate", &Engine::simulate)
        .function("getTick", &Engine::getTick)
        .function("getStatistics", &Engine::getStatistics)
        .function("getGridSnapshot", &Engine::getGridSnapshot)
        .function("getEntityAt", &Engine::getEntityAt)
        .function("getSelectedEntity", &Engine::getSelectedEntity);

    emscripten::register_vector<int>("VectorInt");

    emscripten::value_object<EntityInspectData>("EntityInspectData")
        .field("id", &EntityInspectData::id)
        .field("alive", &EntityInspectData::alive)
        .field("exists", &EntityInspectData::exists)
        .field("x", &EntityInspectData::x)
        .field("y", &EntityInspectData::y)
        .field("type", &EntityInspectData::type)
        .field("hasStats", &EntityInspectData::hasStats)
        .field("hitPoints", &EntityInspectData::hitPoints)
        .field("strength", &EntityInspectData::strength)
        .field("speed", &EntityInspectData::speed)
        .field("hasHunger", &EntityInspectData::hasHunger)
        .field("hunger", &EntityInspectData::hunger)
        .field("hasFuel", &EntityInspectData::hasFuel)
        .field("fuel", &EntityInspectData::fuel)
        .field("hasState", &EntityInspectData::hasState)
        .field("state", &EntityInspectData::state)
        .field("hasDestination", &EntityInspectData::hasDestination)
        .field("destX", &EntityInspectData::destX)
        .field("destY", &EntityInspectData::destY)
        .field("hasInventory", &EntityInspectData::hasInventory)
        .field("rawMeat", &EntityInspectData::rawMeat)
        .field("meals", &EntityInspectData::meals)
        .field("wood", &EntityInspectData::wood)
        .field("hasTarget", &EntityInspectData::hasTarget)
        .field("targetX", &EntityInspectData::targetX)
        .field("targetY", &EntityInspectData::targetY)
        .field("hasFeats", &EntityInspectData::hasFeats)
        .field("slainDeer", &EntityInspectData::slainDeer)
        .field("choppedTrees", &EntityInspectData::choppedTrees)
        .field("foodAte", &EntityInspectData::foodAte)
        .field("mealsCooked", &EntityInspectData::mealsCooked)
        .field("hasKnowledge", &EntityInspectData::hasKnowledge)
        .field("hasClosestFood", &EntityInspectData::hasClosestFood)
        .field("closestFoodX", &EntityInspectData::closestFoodX)
        .field("closestFoodY", &EntityInspectData::closestFoodY)
        .field("hasClosestTree", &EntityInspectData::hasClosestTree)
        .field("closestTreeX", &EntityInspectData::closestTreeX)
        .field("closestTreeY", &EntityInspectData::closestTreeY)
        .field("hasClosestDeer", &EntityInspectData::hasClosestDeer)
        .field("closestDeerX", &EntityInspectData::closestDeerX)
        .field("closestDeerY", &EntityInspectData::closestDeerY)
        .field("hasClosestGrass", &EntityInspectData::hasClosestGrass)
        .field("closestGrassX", &EntityInspectData::closestGrassX)
        .field("closestGrassY", &EntityInspectData::closestGrassY);
}